### ISSUE TITLE
include the main description (of the applied legend manifest) in the generated dashboard too

### ISSUE THREAD

**Issue by yashvardhan-kukreja** [grofers/legend#69]
**Is your feature request related to a problem? Please describe.**
Currently, the dashboard created just prints out the service description of the individual services but there isn't any section in it to display the user-provided description for the dashboard they intend to create.
```yaml
---
title: SampleTitle
service: SampleService
grafana_folder: SampleFolder
description: Logging tool for everything deployed on kubernetes ### this description is not printed anywhere in the dashboard as of now
...
```

**Describe the solution you'd like**
Print out the main user-provided description (of the user-applied legend manifest) under the service descriptions panel as well.

**Describe alternatives you've considered**
Alternatively, a new panel dedicated to the main description could be created as well but that would rupture the currently established structure of dashboards. So, just printing out the main description under the service descriptions panel makes more sense.

**Additional context**
-
